Fix savings on android
rainbow-me/rainbow pull request #1332
Opened 2020-11-19 17:57 UTC by brunobar79

A hack on top of @osdnk hack to get the ripple working without breaking the onPress behavior

PoW: http://recordit.co/nhFgwONFaP

2020-11-19 18:00 UTC, osdnk approved these changes
o, I just came across this!

2020-11-19 18:01 UTC, osdnk commented
or wait

2020-11-19 18:03 UTC, osdnk requested changes
![image](https://user-images.githubusercontent.com/25709300/99705293-35c36b00-2aa2-11eb-9464-6a2161a70574.png)
please just alter this line

https://github.com/rainbow-me/rainbow/pull/1332/files#diff-c67c188b0dd37aeda3c32a1770e4a9308986b74561e6230e435bf60e51b1bf62R172

2020-11-20 06:54 UTC, brunobar79 commented
@osdnk  This one is ready 2 go

2020-11-20 16:48 UTC, osdnk approved these changes
nit

2020-11-20 16:48 UTC, osdnk commented on src/components/savings/SavingsListRow.js
> +            onPress={android ? onButtonPress : NOOP}
```suggestion
            onPress={onButtonPress}
```

I this it's sufficient, cause `Row` does not have onPress

2020-11-20 17:16 UTC, merged