fix sheet height for no data on charts - android
rainbow-me/rainbow pull request #1359
Opened 2020-11-24 00:08 UTC by skylarbarrera

before: https://cloud.skylarbarrera.com/Screenshot_20201123-170316_Rainbow.jpg

after:
      android: https://cloud.skylarbarrera.com/Screen_Recording_20201123-165848.mp4
      ios: https://cloud.skylarbarrera.com/Screen-Recording-2020-11-23-16-54-54.mp4

2020-11-28 02:06 UTC, osdnk requested changes

2020-11-28 02:06 UTC, osdnk commented on src/components/expanded-state/ChartExpandedState.js
> +  const ChartExpandedStateSheetHeight =
How it possible that this var matters? Don't you have a name collision?

Also, will it work with the case when charts are initially not visible, then fetched after e.g. 5 seconds? The reason I made it not dynamically adjusting the size is that we're not able to modify it after opening (at least for now)

2020-11-30 20:53 UTC, skylarbarrera commented
Merging per @christianbaroni , @osdnk I think we should be able to gauge if we're able to show chart before render based on balanceCoinRow's  % change & price = 0, leaving for now as this requires some refactoring and you may have better solution when we refactor sheets

2020-11-30 20:53 UTC, merged

2020-11-30 20:57 UTC, christianbaroni commented
> Merging per @christianbaroni , @osdnk I think we should be able to gauge if we're able to show chart before render based on balanceCoinRow's % change & price = 0, leaving for now as this requires some refactoring and you may have better solution when we refactor sheets

I’ve occasionally seen empty % change values with chart data still available

So if we go this route we should keep the existing chart check on open to catch that case