📌  Pinning issues
rainbow-me/rainbow pull request #1370
Opened 2020-11-24 21:23 UTC by skylarbarrera

Fixes RAI-956 📌 Pinning issues

Proof: https://cloud.skylarbarrera.com/Screen_Recording_20201124-141642.mp4

2020-11-27 17:59 UTC, osdnk requested changes
i don't understand this PR. Can you add some desc?

2020-11-28 09:33 UTC, osdnk commented
I'm sorry. I think I was tired yesterday and this might sound rude. 
Code looks correct, but can you please use some more descriptive variables so I can easily understand what's going on w/o reading issue?

2020-12-08 10:29 UTC, osdnk approved these changes

2020-12-09 02:04 UTC, christianbaroni approved these changes
works great 👍

2020-12-09 02:44 UTC, merged