add locks to transaction related redux actions
rainbow-me/rainbow pull request #2407
Opened 2021-09-16 19:01 UTC by estebanmino

This PR intends to fix the disappearing tx bug adding a lock to all methods that dispatch transactions actions. The main theory we have is that a race condition is happening somewhere I wasn't able to locate, this situation could be updating the transaction state with missing txs and therefore disappearing on the tx list.

![image](https://user-images.githubusercontent.com/12115171/133669485-a9d3b43c-71de-4a06-9e08-346b964024e4.png)

2021-09-17 17:55 UTC, brunobar79 approved these changes
Code LGTM! 

I'd be very careful with QA and try all types of transactions
=> Send ETH (L1 / L2)
=> Send ERC20s
=> Send NFTs
=> Swaps & Savings Deposits
=> WalletConnect contract interactions
=> Multiple txs (ex. send one with normal and another one with fast before the 1st one confirms)

CC: @skylarbarrera

2021-09-17 17:55 UTC, brunobar79 commented on package.json
> +    "async-mutex": "^0.3.2",
remove the caret

2021-09-17 19:19 UTC, jinchung requested changes
Hey can we follow the pattern that is recommended by the `async-mutex` library?
Namely:
1. Making sure there is a try/finally block around the code of interest to enforce release of the lock (otherwise, there could be an error thrown and we deadlock)
2. The current pattern uses the manual acquire and release which has risks in development (forgetting to do the "release" as we move code around) - vs using the `runExclusive`

2021-09-20 15:25 UTC, estebanmino commented
@jinchung @brunobar79 updated with the suggested changes!

2021-09-20 17:33 UTC, skylarbarrera commented
looks like this is messing with L2 transaction approvals, these transactions were confirmed for >10 min

https://user-images.githubusercontent.com/29204161/134047622-1beeac31-c00c-4f0b-baee-06b728ba8a78.mov

2021-09-20 22:43 UTC, estebanmino commented
@skylarbarrera nice catch! I think it was because the provider was defaulting to the web3Provider which is on mainnet so the tx couldn't be found, I could repro and is fixed now

2021-09-21 17:37 UTC, skylarbarrera approved these changes
💯

2021-09-22 00:37 UTC, mikedemarais commented on package.json
> +    "async-mutex": "^0.3.2",
the caret nazi strikes again

2021-09-22 13:18 UTC, jinchung approved these changes
🌮 

approve pending confirmation of `network` always existing on pending txn

2021-09-22 13:27 UTC, jinchung commented
Since NewTransaction type technically has an optional network value, then we can default the `getProviderForNetwork` to using `mainnet` @brunobar79 

Also, we can move towards using `getProviderForNetwork` instead of `web3Provider` fallbacks in places to have a safer pattern so devs don't need to "remember" this pattern

2021-09-23 17:46 UTC, estebanmino commented on package.json
> +    "async-mutex": "^0.3.2",
lol

2021-09-24 10:08 UTC, jinchung commented on src/parsers/transactions.ts
> +        network,
🤔 hmmm

2021-09-24 13:45 UTC, jinchung approved these changes
🌮

2021-09-24 13:57 UTC, merged