🤖 stuff
rainbow-me/rainbow pull request #2494
Opened 2021-10-28 20:49 UTC by skylarbarrera

fixes:
- LP Sheet height + scrolling ( should be able to scroll all of the content)
- swap currency list should still show when tapping the info or rainbow verifies buttons (before it was showing a loading state), fav button should work( its slow). Query should still reset when going back to the sheet(select input and go back to select a new one)
- L2 disclaimer should look the same as iOS, component in the l2 expanded states
- Walletconnect should show full sheet + gas (it was cut off before) make sure to check connect sign + tx
- Switching the lists on discover should not impact the display of the DPI button( before the trading at $x was being cut off)
- last NFT family should be on top of the swap/send fabs vs underneath when collapsed, check dame.eth
- Transaction list should have the same spacing as iOS, before it was not centered

2021-10-28 21:12 UTC, osdnk submitted a review, later dismissed

2021-10-28 22:19 UTC, brunobar79 submitted a review, later dismissed

2021-11-12 22:59 UTC, brunobar79 commented on src/components/value-chart/Chart.js
> +              hapticsEnabled={ios}
no

2021-11-22 22:11 UTC, brunobar79 approved these changes

2021-12-06 08:33 UTC, osdnk approved these changes
I feel I was reading this already a few times and this is good. Looks like no-op on iOs

2021-12-06 10:10 UTC, osdnk commented
I opt for deferring QA for later

2021-12-06 18:39 UTC, ibrahimtaveras00 requested changes
Only issue is that tapping fav button doesn't work on swap currency list, otherwise all other issues are fixed

2021-12-06 18:57 UTC, ibrahimtaveras00 approved these changes
👍🏽

2021-12-07 03:16 UTC, merged

2021-12-07 11:35 UTC, terrysahaidak reviewed
LGTM