fix back up sheet height
rainbow-me/rainbow pull request #2509
Opened 2021-11-02 23:30 UTC by skylarbarrera

My fault 😅

PoW: https://cloud.skylarbarrera.com/Screen-Shot-2021-11-02-at-7.27.29-PM.png

QA: make sure backup manual sheet height's are correct on ios & android

2021-11-03 07:14 UTC, brunobar79 approved these changes

2021-11-04 21:59 UTC, ibrahimtaveras00 requested changes
Looks good on normal + bigger screens, however, on a smaller device I cannot see the "I've saved these words" button nor can I scroll thus am blocked from doing the manual back up 

seen here:
Prod on left, this branch on right

![image](https://user-images.githubusercontent.com/41752922/140426238-d3438073-a119-4406-9938-352885407f9c.png)

2021-11-05 16:22 UTC, skylarbarrera commented
fixes RNBW-1817

2021-11-12 23:17 UTC, ibrahimtaveras00 approved these changes
Fix looks good now on smaller devices, QA Passed 👍🏽

2021-11-12 23:24 UTC, brunobar79 approved these changes

2021-11-12 23:25 UTC, merged