Do not use Svgs on the main screen and hooks
rainbow-me/rainbow pull request #2566
Opened 2021-11-18 01:25 UTC by osdnk

2021-11-18 15:29 UTC, terrysahaidak submitted a review, later dismissed
Overall looks good. I would implement "shouldComponentUpdate"  to the SvgImage component to avoid any rerenders.

2021-11-18 21:23 UTC, skylarbarrera commented
new things:  
- I imagine we want to have a border radius to match on the expanded state: https://cloud.skylarbarrera.com/Screen-Shot-2021-11-18-14-16-40.26.png
- persistentDominantColors are off -  doesn't seem like we're grabbing from the svgToPng url when we convert it, I wonder if we should add that logic into the image or card components so we have it up front when opening the expanded state: https://cloud.skylarbarrera.com/Screen-Shot-2021-11-18-14-17-03.97.png

2021-11-23 01:06 UTC, brunobar79 requested changes
all good except deps!

2021-11-23 01:06 UTC, brunobar79 commented on package.json
> +    "cloudinary": "^1.27.1",
Exact match!

2021-11-23 01:06 UTC, brunobar79 commented on src/handlers/svgs.js
> +  CLOUDINARY_CLOUD_NAME as cloudName,
You need to PR this ones to .env repo and also add them in CI

2021-11-23 03:52 UTC, brunobar79 submitted a review, later dismissed
LGTM!

2021-11-23 04:22 UTC, brunobar79 submitted a review, later dismissed

2021-11-23 19:02 UTC, ibrahimtaveras00 commented
As @skylarbarrera has mentioned above, there are some groups that don't show up at all such as The Colors (thecolors.art) on skillet.eth 

![Screen Shot 2021-11-23 at 1 16 59 PM](https://user-images.githubusercontent.com/41752922/143087052-c05920d0-15c6-479d-8a7e-3ad8fb8983b7.png)

In some instances, if I kill the app and relaunch sometimes it does load but only for certain groups.

If we're ok with this for this PR I'd say we're good to pass.  WDYT @osdnk?

2021-11-23 19:08 UTC, ibrahimtaveras00 approved these changes

2021-11-23 19:24 UTC, merged