@benisgold/helpers memoization
rainbow-me/rainbow pull request #2685
Opened 2021-12-14 18:21 UTC by benisgold

This PR applies `memoFn` from https://github.com/rainbow-me/rainbow/pull/2637 to relevant functions within src/utils.

2021-12-14 18:29 UTC, skylarbarrera commented on src/helpers/time.js
> +  console.log("zooooo");
ser i love zoos but not with my rainbo's

2021-12-14 18:29 UTC, skylarbarrera commented on src/helpers/utilities.ts
> +  console.log("zoopy");
soupy

2021-12-14 18:30 UTC, skylarbarrera approved these changes
lgtm after rm logs & linting

2021-12-15 10:21 UTC, terrysahaidak requested changes
All is good except for my coment

2021-12-15 16:46 UTC, closed without merging