Make AssetListItemSkeleton a functional component
rainbow-me/rainbow pull request #2750
Opened 2021-12-26 22:18 UTC by osdnk

Fixes RNBW-2083

## What changed (plus any additional context for devs)

The list got rewritten to the new version. Ne visual changes. 

## PoW (screenshots / screen recordings)

https://streamable.com/anql8n

## Dev checklist for QA: what to test

See assets' list  before loading

2021-12-27 17:19 UTC, brunobar79 approved these changes
🔥🔥🔥

2021-12-29 11:01 UTC, terrysahaidak requested changes
Few very minor changes and it's good

2021-12-29 11:01 UTC, terrysahaidak commented on src/components/asset-list/AssetListItemSkeleton.js
> +                {...position.sizeAsObject('100%')}
It's better to use style for this. Also make sure to extract it into a constant

2021-12-29 12:33 UTC, terrysahaidak approved these changes

2021-12-29 12:40 UTC, merged