Fix loading state in DiscoverSheet
rainbow-me/rainbow pull request #2827
Opened 2022-01-14 15:27 UTC by osdnk

Fixes RNBW-2215

This fixes a few issues:

1. The ghost is cut-off, this is just a CSS issue. This reverts #2137, but I tested and the original issue is gone anyway
2. While loading, the ghost should not be visible, because the content might still appear. We show the ghost only when loading is done/failed.
3. While fetching a new query with having some results already (e.g., when I inputted `USD` and now I add `C` to `USDC` we should keep the old results until new results will appear. Otherwise, we see an empty state for a short while, which is weird. 

## What changed (plus any additional context for devs)

## PoW (screenshots / screen recordings)
BEFORE:
https://streamable.com/7jioo0

AFTER:
https://streamable.com/6j3jgo

## Dev checklist for QA: what to test

## Final checklist
[ ] Assigned individual reviewers?
[ ] Added labels?

2022-01-14 19:24 UTC, derHowie approved these changes
👍

2022-01-14 21:40 UTC, skylarbarrera approved these changes
🔥

2022-01-14 22:55 UTC, derHowie approved these changes

2022-01-14 23:34 UTC, skylarbarrera approved these changes
👌

2022-01-15 00:08 UTC, jinchung commented
When typing in a query with no results, then typing character by character after that initial query, it flashes the previous result before going back to no result, back and forth: https://recordit.co/nTy8n4foam

2022-01-17 16:30 UTC, jinchung requested changes
Just wanted to move this into "request changes" so that Skylar can add a few tweaks so others don't merge quite yet!

2022-01-18 00:44 UTC, jinchung commented on src/components/exchange/CurrencySelectionList.js
> +            loading ? null : (
it will never reach line 68 bc `!loading` is specified on line 67

2022-01-18 00:47 UTC, jinchung commented on src/components/exchange/CurrencySelectionList.js
> +            loading ? null : (
@osdnk

2022-01-18 00:52 UTC, jinchung reviewed
On the very first time when I open search and search for a token that has no results (e.g, "Vowevadsf"), it just shows the loading shimmer forever. If I delete it and then type it again, THEN it shows me the ghost.

2022-01-18 00:53 UTC, jinchung commented
Mentioned to Skylar: I had merged his PR for ENS handling, but as of now when I search for "jackson" and see the ENS results, then I replace it with some gibberish, the ENS results still hang out

2022-01-18 14:28 UTC, osdnk commented
Fixes https://linear.app/rainbow/issue/RNBW-2252/serach-bar-is-not-fixed-while-searching-on-android

2022-01-19 20:02 UTC, jinchung approved these changes
🌮

2022-01-19 20:42 UTC, skylarbarrera commented
send it

2022-01-19 21:09 UTC, merged