Fix welcome screen getting cutoff on smaller phones
rainbow-me/rainbow pull request #2849
Opened 2022-01-19 00:11 UTC by benisgold

Fixes RNBW-1590

## What changed (plus any additional context for devs)
- Added bottom margin to container view

## PoW (screenshots / screen recordings)
iPhone 13 Pro
![Simulator Screen Shot - iPhone 13 Pro - 2022-01-18 at 16 08 41](https://user-images.gith

iPhone SE
![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-01-18 at 16 08 44](https://user-images.githubusercontent.com/15272675/150038919-295adec5-c919-40d4-aa15-d6fd486e72bb.png)
ubusercontent.com/15272675/150038912-fe82e2f9-844d-4118-aa4e-e7659fb81d1c.png)

2022-01-19 19:31 UTC, skylarbarrera commented
can we use `isSmallPhone` or `isTinyPhone` from the `useDimensions` hook? looks like its already pulled in and I this is pulling the content down to normal -> large sized screens.

also the linear ticket has an issue with the amount buttons having no horizontal margin, may want to make sure you're using the small SE to test, I think there's a few diff screen sizes there

2022-01-24 14:43 UTC, osdnk requested changes
This is not a good way of fixing it. We should assume that the design for a big phone is correct and fix what's broken for a small one.

2022-01-30 02:05 UTC, benisgold commented
> This is not a good way of fixing it. We should assume that the design for a big phone is correct and fix what's broken for a small one.

Thanks! I applied this fix, and uploaded a new PoW that shows that this PR no longer affects the layout of non-small/tiny phones

2022-01-31 13:30 UTC, osdnk commented on src/components/AddFundsInterstitial.js
> +    <Container isSmallScreen={isSmallPhone || isTinyPhone}>
```suggestion
    <Container isSmallScreen={isSmallPhone}>
```

It's not possible that the phone is tiny, but not small

2022-01-31 16:54 UTC, skylarbarrera commented on src/components/AddFundsInterstitial.js
> +  bottom: ${props => props.isSmallScreen && 80};
can we destructure this instead `({ isSmallScreen }) =>

2022-01-31 16:55 UTC, skylarbarrera approved these changes
merging dev should fix ci

2022-01-31 18:50 UTC, merged

2022-01-31 22:45 UTC, osdnk commented
@benisgold this was merged and obviously broke our CI. Please, do not merge before CI is done

2022-01-31 22:52 UTC, jxom commented
i wonder if we should make it so you can't merge unless all checks (CI) have passed? pretty sure there is a setting in github

2022-02-01 15:44 UTC, osdnk commented
I think we have some moments when we want to ignore those settings (e.g. version bump or when there are a vulnerability or CI breaks). We are afraid of making PR "unmergeable".
So I am opposed to introducing this as a strict requirement. However, this one should not be merged before CI

2022-02-01 15:46 UTC, skylarbarrera commented
> I think we have some moments when we want to ignore those settings (e.g. version bump or when there are a vulnerability or CI breaks). We are afraid of making PR "unmergeable".
> 
> So I am opposed to introducing this as a strict requirement. However, this one should not be merged before CI 

jin added this behavior yesterday, if for some reason shits broken jin + bruno have the ability to merge