Sort connected daaps by most recent handshake
rainbow-me/rainbow pull request #3043
Opened 2022-03-14 01:24 UTC by pugson

Fixes RNBW-2070

## What changed (plus any additional context for devs)
- Added a timestamp to show the latest handshake with dapp
- Changed list sorting to be by most recent handshake
- Fixed L2 icon alignment on Android
- Fixed wallet icon shadow clipping at the bottom of the list on Android

## PoW (screenshots / screen recordings)
|  Before  |  After  |
|---|---|
|  ![Screenshot_20220314-020831](https://user-images.githubusercontent.com/6843656/158088838-0daa3e44-da32-42d6-95e6-061e863e29e9.png) | ![Screenshot_20220314-021003](https://user-images.githubusercontent.com/6843656/158088845-c2ad87cf-fb46-4560-abac-9d6035bb6c5f.png)   |

## Dev checklist for QA: what to test
Connecting wallets, switching networks, switching wallets, signing messages and transactions with connected wallets.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?

2022-03-14 08:43 UTC, osdnk approved these changes
from the code perspective, this is a no-brainer. although I'm not.a fan of negative margins. However, the design review here is more relevant.

2022-03-14 08:43 UTC, osdnk commented on src/helpers/time.js
> + */
Appreciate this, but realistically this is not needed. TS should fix this eventually

2022-03-14 15:54 UTC, pugson commented
oh wow yeah these timestamps should probably go

2022-03-15 23:48 UTC, pugson commented
Newest preview after changes:
![Screenshot_20220316-004507](https://user-images.githubusercontent.com/6843656/158490427-f309fe25-479c-4843-a518-ae81acdd98ff.png)

2022-03-16 15:19 UTC, tchayen requested changes
Doesn't look scary on small phones anymore, but veryveryverylongnames still break layout a bit, even on iPhone 13:

![photo_2022-03-16 17 18 14](https://user-images.githubusercontent.com/5769281/158624711-33a760c1-9453-4c85-b6d5-18cfa2a0ad58.jpeg)

2022-03-16 15:22 UTC, pugson commented
Thanks @tchayen. Will clean this up even though it's out of scope for this ticket but very much an ugly problem.

2022-03-16 17:41 UTC, pugson commented
Ready to merge as-is because there are some more layout issues out of scope. New task for them: https://linear.app/rainbow/issue/RNBW-2843/connected-apps-list-margins-and-alignment-messed-up-on-android

2022-03-16 17:41 UTC, tchayen approved these changes
LGTM :shipit: (pls fix linter)

2022-03-16 20:23 UTC, merged