Update certificates for widgets to allow building on real devices
rainbow-me/rainbow pull request #3097
Opened 2022-03-24 10:56 UTC by osdnk

Fixes RNBW-####

Internal context: https://rainbowhaus.slack.com/archives/CGUDDJYNL/p1648119394600789

## What changed (plus any additional context for devs)

## PoW (screenshots / screen recordings)

## Dev checklist for QA: what to test

## Final checklist

- [ ] Assigned individual reviewers?
- [ ] Added labels?

2022-03-24 21:13 UTC, brunobar79 requested changes
Looks good but changes on release targets needs to be reverted

2022-03-24 21:13 UTC, brunobar79 commented on ios/Rainbow.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "iPhone Developer";
You're setting a development profile to a release target.  I think this will break on CI => Testlight => Prod

2022-03-24 21:13 UTC, brunobar79 commented on ios/Rainbow.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "match Development me.rainbow.PriceWidget";
Same

2022-03-24 21:13 UTC, brunobar79 commented on ios/Rainbow.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "iPhone Developer";
same

2022-03-24 21:13 UTC, brunobar79 commented on ios/Rainbow.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "match Development me.rainbow.SelectTokenIntent";
same

2022-03-24 21:19 UTC, osdnk commented
@brunobar79. right. how about now?

2022-03-24 21:21 UTC, brunobar79 approved these changes
Now it looks good!

I suggest you trigger a testflight build from this branch and make sure the widgets are still working on testflight.  Then it's 100% safe to merge.

2022-03-24 21:22 UTC, osdnk commented
https://app.bitrise.io/build/48605469-1d59-4f9f-b5b0-a266eafcbb0b

2022-03-25 07:35 UTC, tchayen approved these changes

2022-03-25 07:38 UTC, merged