Prevent assets loading in chunks
rainbow-me/rainbow pull request #3180
Opened 2022-04-12 02:20 UTC by jxom

Fixes RNBW-2143

## What changed (plus any additional context for devs)

This PR fixes the jarring "loading tokens in chunks" UI when initializing a wallet for the first time.

Since we are dealing with websockets to retrieve asset data, this makes loading state a bit cumersome to manage. In the ideal world, it would be nice if loading assets would be sync, but since websockets are naturally async, this implementation will have to do for now (unless we want to show a "refetching" floating pill instead of skeleton). 

The implementation involves setting a "debounced" function (with a specified timeout) that sets the loading state to false when we no longer receive any more "received asset" events from the websocket. This only occurs for a wallet loading their assets for the first time (where we see the jank). However, on subsequent wallet loads, it just updates in the background.

## PoW (screenshots / screen recordings)

Before:

https://www.loom.com/share/029baaaf84c74de297cb75e5871900dc

After:

https://www.loom.com/share/49efb12e0ff24cd1b065d502564564b7

## Dev checklist for QA: what to test

1. Open a fresh instance of Rainbow (with no wallets imported)
2. Import accounts with a large number of assets (e.g. "rainbowwallet.eth")

2022-04-12 05:29 UTC, jxom commented on src/redux/data.ts
> +const FETCHING_TIMEOUT = 10000;
posting slack thread here for context:
https://rainbowhaus.slack.com/archives/C02C8JQ313N/p1649718532564969

2022-04-20 22:16 UTC, jxom commented on src/redux/data.ts
> +const FETCHING_TIMEOUT = 10000;
yo @brunobar79 @welps – are we happy w/ this implementation for now?

2022-04-20 23:01 UTC, welps commented on src/redux/data.ts
> +const FETCHING_TIMEOUT = 10000;
Sorry, was I blocking this?

2022-04-20 23:01 UTC, welps approved these changes

2022-04-20 23:30 UTC, jxom commented on src/redux/data.ts
> +const FETCHING_TIMEOUT = 10000;
not really, just need some approvals!

2022-04-21 05:16 UTC, skylarbarrera commented
/preview

2022-04-21 17:19 UTC, skylarbarrera approved these changes
this is very nice ty 🙏

2022-04-29 16:46 UTC, ibrahimtaveras00 requested changes
I'm seeing behavior that when I switch in between vitalik.eth (watching) and rainbowwallet.eth (owner) a lot of vitalik.eth assets are showing up instead; seen here = https://recordit.co/tdUiy4Avay

![Screen Shot 2022-04-29 at 12 43 07 PM](https://user-images.githubusercontent.com/41752922/165987839-6ff9f83f-e6e0-4a86-98b9-c011ae154a85.png)

steps:
- fresh install (0 wallets) 
- watch vitalik.eth 
- import rainbowwallet.eth 
- switch in between the 2 accounts

2022-05-02 18:52 UTC, jinchung commented
status update: reached out to jake, ibrahim, skylar for next steps and verifying token wallet mixup still an issue

2022-05-03 22:48 UTC, jxom commented
@ibrahimtaveras00 – try now?

2022-05-03 23:58 UTC, ibrahimtaveras00 approved these changes
Looks good now, QA Passed 👍🏽

2022-05-04 01:21 UTC, merged