image handling fixes + refactor
rainbow-me/rainbow pull request #3188
Opened 2022-04-13 16:53 UTC by skylarbarrera

Fixes RNBW-2730 RNBW-2917

## What changed (plus any additional context for devs)
fixes some regressions from https://github.com/rainbow-me/rainbow/commit/3eac3a97f1980b61bb0380889c820ddd780a36b4 (low res image handling/progressive loading, certain NFTs not animating properly) 

as well as refactors image/svg handling/signing so its all in one place and is handled upfront rather than in 4 diff spots of the app 

## PoW (screenshots / screen recordings)

## Dev checklist for QA: what to test

all NFTs in `skillet.eth` (aside from genesis bags) should load on asset screen, and when opening the expanded state should open with the image already preloaded 

few edge cases we want to check:
Loot in `dame.eth`
Max Pain in `0x58A4368a73196921e236f663388A96A209b64EE5`
Peaceful in `jdelman.eth`
## Final checklist

- [ ] Assigned individual reviewers?
- [] Added labels?
- [x] Added e2e tests? if not please specify why: just bug fixes
- [] If you added new files, did you update the CODEOWNERS file?

2022-04-14 14:50 UTC, skylarbarrera commented
/preview

2022-04-14 17:18 UTC, skylarbarrera commented
/preview

2022-04-14 18:19 UTC, brunobar79 commented
> andling/signing so its all in one place and is handled upfront rather than in 4 diff spots of the app



> /preview

rugged by fedora

2022-04-14 18:49 UTC, brunobar79 requested changes
Code looks ok, but there's seems to be a regression with POAP previews and UNIv3 positions.  You can try djweth.eth

This branch
![IMG_1317](https://user-images.githubusercontent.com/1247834/163456998-5688819b-221e-4e64-a905-062ef9f0b58c.PNG)

Prod:
![IMG_1318](https://user-images.githubusercontent.com/1247834/163457020-a11b5d17-3316-4a97-9aee-0b3d931c7c4c.PNG)

2022-04-14 19:57 UTC, skylarbarrera commented
@brunobar79 ty ser should be good to go now

PoW: https://cloud.skylarbarrera.com/Screen-Recording-2022-04-14-15-54-07.mp4

2022-04-14 19:57 UTC, skylarbarrera commented
/preview

2022-04-14 20:28 UTC, brunobar79 approved these changes
🔥🔥🔥

2022-04-14 22:21 UTC, terrysahaidak commented on src/parsers/uniqueTokens.js
> +          urlSuffixForAsset: `${get(asset_contract, 'address')}/${token_id}`,
can we get rid of `get` here since you're touching this code and optional chaining is used already?

2022-04-14 22:21 UTC, terrysahaidak approved these changes
Left a comment, but looks good overall!

2022-04-15 01:33 UTC, ibrahimtaveras00 approved these changes
Fixes look good, QA Passed 👍🏽

2022-04-15 19:39 UTC, jinchung approved these changes
🌮

2022-04-15 19:39 UTC, merged