Android Back Up Input blurring
rainbow-me/rainbow pull request #3279
Opened 2022-05-02 09:43 UTC by perunt

Fixes RNBW- RNBW-3405

## What changed (plus any additional context for devs)
You can change the display size in several gradations in the phone settings. If you set the display size more than the default, the text in the app will also increase, and the proportions will change.
I use the same solution as for small screens by hiding the icon from the screen

## PoW (screenshots / screen recordings)
before:
 - [pixel 5](https://streamable.com/nromee)
 - [pixel 4](https://streamable.com/am566f)
 after:
 - [pixel 4](https://streamable.com/7hftq2)
## Dev checklist for QA: what to test

## Final checklist
Try to backup a wallet
- [ ] Assigned individual reviewers?
- [ ] Added labels?
- [ ] Added e2e tests? if not please specify why
- [ ] If you added new files, did you update the CODEOWNERS file?

2022-05-02 18:08 UTC, osdnk approved these changes

2022-05-05 11:02 UTC, tchayen requested changes
I can't reproduce the problem 😬.

I have one suggestion about the code.

2022-05-05 11:16 UTC, terrysahaidak commented on src/components/backup/RestoreCloudStep.js
>    const { isTinyPhone } = useDimensions();
```suggestion
  const { isTinyPhone, scale } = useDimensions();
```

2022-05-05 11:38 UTC, perunt commented
@tchayen yes, you're right, it doesn't matter here. 
You can see that on Android. Just set one of the largest display sizes in phone settings

2022-05-05 11:56 UTC, terrysahaidak approved these changes

2022-05-09 16:14 UTC, tchayen approved these changes
I still can't reproduce the problem on my testing phone, but also it's not breaking anything so 👌.

2022-05-10 08:16 UTC, jkadamczyk approved these changes

2022-05-15 16:56 UTC, merged