mare 4 basic ops numbers
rainbow-me/rainbow pull request #3289
Opened 2022-05-03 14:08 UTC by osdnk

Fixes RNBW-####

## What changed (plus any additional context for devs)

## PoW (screenshots / screen recordings)

## Dev checklist for QA: what to test

## Final checklist

- [ ] Assigned individual reviewers?
- [ ] Added labels?
- [ ] Added e2e tests? if not please specify why
- [ ] If you added new files, did you update the CODEOWNERS file?

2022-05-04 05:49 UTC, osdnk commented on src/hooks/useSavingsAccount.js
> +  }));
yes! Previously we were parsing those strings around 1000 times. This is happening once

2022-05-04 05:50 UTC, osdnk commented on src/helpers/utilities.ts
> +  if (typeof numberOne === 'number' && typeof numberTwo === 'number') {
yea, I forgot to remove some loeftover from this file

2022-05-04 05:54 UTC, osdnk commented on src/helpers/buildWalletSections.js
> +    totalUnderlyingNativeValue = underlyingBalanceNativeValue || 0;
yea, but this doesn't make sense. 5 lines above we set `totalUnderlyingNativeValue` to 0

2022-05-04 05:56 UTC, osdnk commented on src/helpers/utilities.ts
> +): number => {
I checked a lot of places and this was ok. I think this is similar to tour change BigNumbers -> String

2022-05-04 05:57 UTC, osdnk commented on src/helpers/utilities.ts
> +  const numberOneAsNumber =
I would avoid this

2022-05-04 08:10 UTC, osdnk commented on src/helpers/utilities.ts
> +  const numberOneAsNumber =
2 reasons:
This is in total saving us maybe 5 lines.
If this is so much about optimization, I would avoid extra function call

2022-05-16 09:29 UTC, osdnk commented
\rebase

2022-05-17 08:11 UTC, jkadamczyk commented on src/handlers/ens.ts
> +      (a, b) => add(a || 0, b || 0),
Why not use optional chaining here?

2022-05-17 08:20 UTC, jkadamczyk approved these changes
Looks good to me!
Left a couple of nits only

2022-05-17 08:20 UTC, jkadamczyk commented on src/handlers/ens.ts
> +      (a, b) => add(a || 0, b || 0),
Why not use nullish coalescing here?

2022-05-17 08:20 UTC, jkadamczyk commented on src/handlers/ens.ts
> +  const gasLimit = gasLimits.reduce((a, b) => add(a || 0, b || 0), 0);
Same
Why not use nullish coalescing here?

2022-05-17 08:20 UTC, jkadamczyk commented on src/helpers/buildWalletSections.js
> +    totalUnderlyingNativeValue = underlyingBalanceNativeValue || 0;
Why not use nullish coalescing here?

2022-05-17 10:14 UTC, osdnk commented
@jkadamczyk regarding all your comments - no profound reason, I didn't change what was not necessary, but sure, I'll make it with nullish coalescing

2022-05-18 10:57 UTC, osdnk commented
/rebase

2022-05-23 14:31 UTC, brunobar79 approved these changes
Added one minor comment, otherwise LGTM!

2022-05-23 19:45 UTC, osdnk commented on src/entities/tokens.ts
> +    amountNum?: number;
Unfortunately we need this exactly when we need to send eventing (max button)

2022-05-30 10:40 UTC, terrysahaidak approved these changes
All good!

2022-05-30 10:40 UTC, terrysahaidak commented on src/helpers/savings.js
>  const formatSavingsAmount = memoFn(amount => {
i think we don't need memo anymore

2022-06-02 15:44 UTC, estebanmino approved these changes
@osdnk let us know if you need someone from profiles to take a look, I did try this and it was working correctly after updating some methods

2022-06-06 07:11 UTC, osdnk commented
/rebase

2022-06-23 21:32 UTC, ibrahimtaveras00 requested changes
Some issues from QA: 
- https://linear.app/rainbow/issue/RNBW-3899/[remove-bignumbersjs-3289]-android-gast-estimation-issues
- https://linear.app/rainbow/issue/RNBW-3900/[remove-bignumbersjs-3289]-error-on-expanding-savings-section
- https://linear.app/rainbow/issue/RNBW-3901/[remove-bignumbersjs-3289]-speed-up-and-cancel-renders-an-error
- https://linear.app/rainbow/issue/RNBW-3902/[remove-bignumbersjs-3289]-wc-approve-request-not-working
- https://linear.app/rainbow/issue/RNBW-3903/[remove-bignumbersjs-3289]-nothing-happens-when-attempting-deposit-and

2022-07-07 19:32 UTC, ibrahimtaveras00 requested changes
Just two outstanding issues from the bug fix QA:

**Issue 1:**

Issue 2 from RNBW-3899 is still occurring, seen here = http://recordit.co/c0wSylJXdX

**Issue 2:** 

The activity list shows as empty when I should have txn's populating on a fresh install of android and after clearing cache on iOS; seen here = https://recordit.co/Zqysx7U8z7

2022-07-08 21:54 UTC, ibrahimtaveras00 requested changes
Issue 1 = max base fee still changes when editing miner tip = http://recordit.co/qlSPrIq354

Issue 2 = fixed

2022-07-14 15:31 UTC, osdnk commented
/testflight

2022-07-14 15:32 UTC, osdnk commented
/preview

2022-07-14 15:38 UTC, osdnk commented
/testflight

2022-07-14 16:06 UTC, ibrahimtaveras00 approved these changes
I saw the last issue get fixed from @osdnk on both OS's, everything looks good 👍🏽

2022-07-14 16:07 UTC, merged