Crash when filled a lot of digits in the swap input
rainbow-me/rainbow pull request #3336
Opened 2022-05-13 16:56 UTC by perunt

Fixes RNBW-3575

## What changed (plus any additional context for devs)
The crash occurred after entering more digits than the coin can split.
Can be reproduced by entering 0.123456789 for Wrapped Bitcoin into swap inputs
- `Compound DAI ` - 8 decimals
- `Wrapped Bitcoin` - 8 decimals
- `Ethereum` - 18 decimals

## PoW (screenshots / screen recordings)
before: https://user-images.githubusercontent.com/48593211/168335446-1138146b-d161-4ded-8727-7b8082dcf502.mp4
after: https://user-images.githubusercontent.com/48593211/168335564-4c7314a4-d0ef-42dc-a1e7-1b7a118348e8.mp4

## Dev checklist for QA: what to test
swap inputs

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why
- [x] If you added new files, did you update the CODEOWNERS file?

2022-05-16 08:54 UTC, osdnk requested changes
i don't think we should do a try-catch.


Imagine someone typing `0.123456789123123` and then changing the first number to ` 1.123456789123123`. The changes will not be reflected, right? Why this break? Can't we just fix this using rounding or big numbers?

2022-05-16 13:25 UTC, perunt commented
@osdnk 
this only applies to the number of decimal places, the total number can contain more characters

for example, in wrapped bitcoin with 8 digits:
`0.12345678` -> valid (and will be displayed in the equivalent of another coin in the neighboring input)
`12345.12345678` -> valid (and will be displayed)

`0.123456789` - not valid (will not be displayed)
`12345.123456789` - still not valid and will not be displayed

Okay, I can try rounding the values while the user enters them.

2022-05-19 15:10 UTC, brunobar79 commented
FYI: All this code will be thrown away soon once #2763  gets merged.
Already tested this scenario and it doesn't crash http://recordit.co/XuziqABkzj

So maybe we can hold on ?  rounding user input  is a very delicate topic that can result in lost funds.

2022-05-20 07:26 UTC, perunt commented
it makes sense for me, so I will close this pr if @osdnk doesn't mind

2022-05-27 16:24 UTC, perunt commented
I move it to draft and when [2763](https://github.com/rainbow-me/rainbow/pull/2763) is merged I will close this one

2022-07-15 02:38 UTC, closed without merging

2022-07-15 15:07 UTC, jinchung commented
@perunt confirmed this is fixed in the latest swaps branch - closing and deleting this branch