Part of lodash replacement. Replace find
rainbow-me/rainbow pull request #3352
Opened 2022-05-17 13:22 UTC by perunt

Fixes RNBW-3661

## What changed (plus any additional context for devs)
Use a native filter for array, for obj just  `Object.values` and do filter too
it's several times faster than lodash one

## PoW (screenshots / screen recordings)

## Dev checklist for QA: what to test

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why
- [x] If you added new files, did you update the CODEOWNERS file?

2022-05-17 19:22 UTC, skylarbarrera approved these changes

2022-05-18 11:00 UTC, osdnk requested changes
Please, do not use the `i` variable and review if optional chaining is needed (e..g, in `src/utils/ethereumUtils.ts` it's obvious it's not I guess)

2022-05-18 17:18 UTC, perunt commented on src/handlers/walletReadyEvents.ts
>    const rainbowWalletsNotBackedUp = filter(wallets, wallet => {
something like that. I thought that the smaller a pr the sooner you will look at it, but now I began to doubt
in the next one I will combine methods

2022-05-23 15:14 UTC, brunobar79 approved these changes
🚀 🚀 🚀

2022-05-23 15:15 UTC, osdnk approved these changes

2022-05-24 14:00 UTC, merged