[TEAM2-19] Wallet connect confirmation screen should use metadata service
rainbow-me/rainbow pull request #3608
Opened 2022-06-28 16:02 UTC by salman-rb

## What changed (plus any additional context for devs)
We changed the transactions list screen to use our metadata backend service in https://github.com/rainbow-me/rainbow/pull/2990, this PR extends the usage to the WC transaction confirmation screen. Still use the on-chain registry as a fallback, but should be rare to hit unless the backend is down/times out, backend also hits the on chain registry. This will allow us to more tightly control poor user experiences like this one:

![image](https://user-images.githubusercontent.com/98344978/176225271-45178a21-9359-4a84-9cf3-ec74d7a6f0a5.png)

## PoW (screenshots / screen recordings)
Tested manually, no UI change.

## Dev checklist for QA: what to test
Check that the function name on the WC confirmation screen is present. For some reason I can't always trigger the resolution, maybe sometimes the data passed in https://github.com/rainbow-me/rainbow/blob/68c2af6a019442bf3fe663eea723f321423bf763/src/screens/TransactionConfirmationScreen.js#L328 is empty? Not sure why.

2022-06-29 01:51 UTC, welps requested changes
Tested fine for me, but I think you need to remove the lodash usage + fix lint

<img href="https://user-images.githubusercontent.com/677680/176333478-eac32200-9d35-4581-91ed-47d38e548157.jpg" width=25% />
<img href="https://user-images.githubusercontent.com/677680/176333479-7c53d3dd-efac-4c2c-a215-cccd89cd8ff6.jpg" width=25% />
<img href="https://user-images.githubusercontent.com/677680/176333481-c178112b-2899-4904-ace3-a03449f1fc60.jpg" width=25% />

2022-06-29 02:17 UTC, welps commented
/preview

2022-07-05 23:01 UTC, welps approved these changes

2022-07-11 15:26 UTC, estebanmino approved these changes
looking good! 🔥  tried on a couple of dapps

2022-07-11 16:02 UTC, estebanmino commented
/rebase

2022-07-12 23:43 UTC, ibrahimtaveras00 approved these changes
Looks good on both OS's

2022-07-13 00:31 UTC, merged