swaps: add loading check to confirm button
rainbow-me/rainbow pull request #3754
Opened 2022-07-19 21:08 UTC by skylarbarrera

Fixes TEAM2-264
Figma link (if any):

## What changed (plus any additional context for devs)
wasn't able to repro but from the logic it seems we needed some loading checks to be added to prevent authorizing to be set to true to early

## Screen recordings / screenshots

## What to test

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

2022-07-19 22:48 UTC, estebanmino requested changes
not really working, @skylarbarrera is taking a look

2022-07-19 23:51 UTC, estebanmino commented
working now

https://user-images.githubusercontent.com/12115171/179867003-125445b4-dfe4-4991-b020-a6ec3efdcce0.mp4

2022-07-19 23:51 UTC, estebanmino approved these changes

2022-07-20 01:04 UTC, jinchung approved these changes
🌮

2022-07-20 01:04 UTC, merged