Fix memory leak in cool modals
rainbow-me/rainbow pull request #3841
Opened 2022-07-27 07:44 UTC by osdnk

Fixes RNBW-####
Figma link (if any):

This was a regression caused by https://github.com/rainbow-me/rainbow/pull/1142

However, the original bug was already fixed in reanimated so this fix is not needed. Also, I expect that this particular line was unintentional anyway 

See the bug here:
before https://streamable.com/em0d2t
![image](https://user-images.githubusercontent.com/25709300/181189830-8359bc35-cce9-4edf-acc8-a714a0be7be4.png)

after: https://streamable.com/nvgoxe
![image](https://user-images.githubusercontent.com/25709300/181189891-19b802ea-680f-428a-be8a-459ef06ed1bc.png)

Observe the memory chart changing: 

Before: https://streamable.com/e0kxpe
After:https://streamable.com/0vkpty

Before after 1 minute 
![image](https://user-images.githubusercontent.com/25709300/181190801-f311196e-ea35-4375-b173-6370599b124a.png)

After fix after almost 2 minutes
![image](https://user-images.githubusercontent.com/25709300/181190885-0aafa4ed-a5d0-476b-a2fd-f32a1bfae50a.png)

(see recording for the more precise experiments documentation) 

There is still something broken (maybe this is just JS logic), but definitely, the derivative of the growth decreased so it's an improvement. 
 
## What changed (plus any additional context for devs)

I restored commented out line cause setting controller to `null`. This is important because in this structure (that is a bit incorrect, but ok) `controller` is holding `view` (`RNCMScreen` and `RNCMScreeView`) and vice versa. This is not java GC, but ARC (not having GC to be precise), which means that as long as the memory holds the reference for the object, it doesn't get deallocated. Here, one object keeps ref to another and the other way.

I fixed this in a way this was supposed to be fixed originally.

2022-07-27 07:52 UTC, osdnk commented on src/react-native-cool-modals/ios/RNCMScreen.m
> +  _controller = nil;
this is the only meaningful change

2022-07-27 07:55 UTC, terrysahaidak approved these changes

2022-07-27 08:26 UTC, tchayen approved these changes

2022-07-27 09:32 UTC, jkadamczyk approved these changes

2022-07-28 15:38 UTC, brunobar79 requested changes
Seems like this is change is breaking e2e

2022-08-01 09:23 UTC, terrysahaidak commented
/rebase

2022-08-08 18:10 UTC, terrysahaidak commented
/rebase

2022-08-24 11:48 UTC, tchayen commented
/rebase

2022-10-17 20:15 UTC, jkadamczyk commented
@estrattonbailey Did you have any intentions with closing and reopening?
I will assign myself to that to see if we can merge it

2022-10-18 15:46 UTC, jkadamczyk commented
It has some issues, we shouldn't merge it in this state. Gonna create linear tickets for that to address the memory leaks and link this PR

Uploading Screen Recording 2022-10-18 at 10.44.07.mov…

2022-10-18 15:46 UTC, closed without merging