Fix select contact issues
rainbow-me/rainbow pull request #3871
Opened 2022-08-01 05:12 UTC by jxom

Fixes RNBW-3948

## What changed (plus any additional context for devs)

Fixed issues around typing/selecting addresses in the Send flow:

- Debounced the input value so we aren't spamming the RPC & confusing the UI
- Eagerly validating the address (via checking if it's in the right format), so we aren't waiting for ENS names to resolve
  - note: the user still won't be able to send the transaction until the address has been validated

## Screen recordings / screenshots

https://www.loom.com/share/f721767c58a9477eab727c6cdefb1f03

## What to test

- Ensure that an ENS name correctly resolves & still able to send transaction,
- Ensure that an Unstoppable Domain name correctly resolves & still able to send transaction,
- Ensure that a plain address correctly resolves & still able to send transaction
- Ensure that you can't send a transaction if the ENS name, UD name or plain address is invalid

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

2022-08-01 05:13 UTC, jxom commented
/testflight

2022-08-03 12:17 UTC, jkadamczyk approved these changes

2022-08-03 12:17 UTC, jkadamczyk commented
Seems like it works for me

2022-08-03 12:52 UTC, pugson approved these changes

2022-08-03 18:00 UTC, estebanmino requested changes
code looks good but the original issue is still there, maybe related to the contacts object?

https://user-images.githubusercontent.com/12115171/182677158-314e3dc3-34e2-44a9-8087-426562b53701.mov

2022-08-03 20:29 UTC, jxom commented
/testflight

2022-08-04 15:48 UTC, estebanmino approved these changes
looking good! i also sent a tx when pressing a contact just in case 🔥

2022-08-04 16:07 UTC, skylarbarrera approved these changes
working 4 m3

2022-08-04 20:08 UTC, merged