Fix avatar placement in picker
rainbow-me/rainbow pull request #3879
Opened 2022-08-01 17:52 UTC by tchayen

Fixes RNBW-4000
Figma link (if any):

## What changed (plus any additional context for devs)

Placement of avatar circle in avatar picker on Android.

## Screen recordings / screenshots

Before 

https://user-images.githubusercontent.com/5769281/182211025-fdcbf59d-14e3-46f1-b4cc-80e321d571b9.mp4

After

https://user-images.githubusercontent.com/5769281/182211057-2a058574-d6df-4966-a3ba-ffdd5fa916e7.mp4

## What to test

Avatar picker on Android and iOS (looking for regression).

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [ ] If no `dev QA` label, did you add the PR to the QA Queue?

2022-08-01 18:59 UTC, osdnk commented
Hey it's good but we agreed to disable picker

2022-08-01 19:09 UTC, terrysahaidak requested changes

2022-08-01 19:09 UTC, terrysahaidak commented on src/navigation/effects.js
> +            top: HeaderHeightWithStatusBar + (android ? 10 : 0),
Well i would exact it into a constant because then it's very easy to actually change in one place and break in another

2022-08-01 20:45 UTC, tchayen commented
Oh, totally forgot about disabling picker. Not sure if we already have a task for that. I will create one.

2022-08-02 09:21 UTC, osdnk approved these changes
I testes and it ok!

2022-08-02 12:06 UTC, perunt approved these changes
Works good

Just to be sure - when I double tap outside the modal, I redirected to Wallet Screen, is that ok?

2022-08-02 13:45 UTC, tchayen commented
@perunt yea it works weird but it's out of scope here.

BTW, for clarity on what is going to happen here – I am planning to merge this as it fixes the problem anyway (and we would have to deal with it in future), but we are going to hide picker for the release.

2022-08-03 10:14 UTC, terrysahaidak approved these changes

2022-08-03 10:20 UTC, merged