Convert menu in switch wallet to the new context menu
rainbow-me/rainbow pull request #3884
Opened 2022-08-02 09:42 UTC by tchayen

Fixes RNBW-4106
Figma link (if any):

## What changed (plus any additional context for devs)

## Screen recordings / screenshots

On iOS nothing changed:

https://user-images.githubusercontent.com/5769281/182343810-28f077f1-6f80-41d7-bfcb-64344b358afe.MP4

On Android the new context menu is used:

https://user-images.githubusercontent.com/5769281/182343868-f412dacc-7edf-45eb-a19f-43458bb677e8.mp4

## What to test

Test all possible cases of editing wallets:
- On iOS it's possible to edit wallet by long pressing even not in edit mode (on Android not).
- It's not allowed to remove wallet when there's only one left.
- And many more which I probably don't know 😬.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [ ] If no `dev QA` label, did you add the PR to the QA Queue?

2022-08-02 10:28 UTC, terrysahaidak commented
on Android context menu should appear from the button that triggers it, on the video its placement is confusing.

2022-08-02 10:34 UTC, tchayen commented
The problem here is that the whole row acts as a button (even though it looks like the button is only on the left).

2022-08-02 15:26 UTC, terrysahaidak commented
@tchayen can you try that prop that tells where to render the menu?

2022-08-03 10:05 UTC, tchayen commented
@terrysahaidak 

![Screenshot_20220803-130401_Rainbow](https://user-images.githubusercontent.com/5769281/182582334-8c23a995-780e-45a6-ac9a-77b91526e97f.jpg)

2022-08-03 10:27 UTC, terrysahaidak approved these changes
Now it's better

2022-08-03 11:32 UTC, osdnk commented
https://streamable.com/z5kj6b

This is very wrong. Let's stick the menu to the small button, not the whole row

2022-08-03 11:32 UTC, osdnk requested changes
^

2022-08-03 12:54 UTC, osdnk approved these changes

2022-08-04 11:54 UTC, perunt requested changes
the new context menu works fine
just one comment about the ability to change wallets

2022-08-04 11:54 UTC, perunt commented on src/components/change-wallet/AddressRow.js
> +      )}
It looks like there is no way to choose another wallet on android

2022-08-05 11:46 UTC, perunt approved these changes
:rocket:

2022-08-05 11:49 UTC, merged