Add LooksRare marketplace link
rainbow-me/rainbow pull request #4188
Opened 2022-09-21 23:24 UTC by jxom

Fixes PAR-42

## What changed (plus any additional context for devs)

This PR adds a link to LooksRare on the NFT expanded state.

## Screen recordings / screenshots

### iOS

https://user-images.githubusercontent.com/7336481/191627001-9580b790-4fd6-4f29-919d-7c38f6dab96b.mp4

### Android

https://www.loom.com/share/0781d0682ea44cb1916bc9c179a7df85

## What to test

- On both iOS & Android, head to the NFT expanded state, press the "..." button and then you should see "View in Marketplaces..."

2022-09-21 23:26 UTC, jxom commented on src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
>          ...(isSupportedOnRainbowWeb
Just moving down the "View on..." menu items here.

2022-09-21 23:27 UTC, jxom commented on src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
> +                menuItems: [AssetActions.opensea, AssetActions.looksrare],
This is the only new addition.

2022-09-22 12:00 UTC, terrysahaidak approved these changes

2022-09-26 13:16 UTC, osdnk requested changes
Please add android screenshots

2022-09-26 19:15 UTC, jxom commented
@osdnk there is an android video in description

2022-10-03 10:29 UTC, pugson approved these changes
looks rare to me 🫡

2022-10-03 20:00 UTC, skylarbarrera approved these changes
👌

2022-10-04 06:10 UTC, osdnk approved these changes

2022-10-12 12:53 UTC, brunobar79 approved these changes

2022-10-12 15:29 UTC, merged