Rainbow Home Screen revamp – 2nd iteration
rainbow-me/rainbow pull request #4195
Opened 2022-09-26 02:31 UTC by jxom

Fixes RNBW-####
Figma link (if any):

## What changed (plus any additional context for devs)

## Screen recordings / screenshots

## What to test

## Final checklist

- [ ] Assigned individual reviewers?
- [ ] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [ ] Did you test both iOS and Android?
- [ ] If your changes are visual, did you check both the light and dark themes?
- [ ] Added e2e tests? If not, please specify why
- [ ] If you added new critical path files, did you update the CODEOWNERS file?
- [ ] If no `dev QA` label, did you add the PR to the QA Queue?

2022-10-06 09:02 UTC, osdnk commented on src/components/qrcode-scanner/CameraDimmer.js
> -  const scrollPosition = usePagerPosition();
why?

2022-10-06 09:08 UTC, osdnk reviewed
you sure that the header in your PR should appear without any animation or anything? That looks quite rough

cc @mikearndt

2022-10-06 09:10 UTC, osdnk reviewed
I approve from the perspective of navigation and RLV. I didn't read yet the whole code, nor run it on the device.

2022-10-06 09:50 UTC, sammdec approved these changes
Reviewed code and tested on ios and android physical devices

2022-10-06 09:50 UTC, sammdec commented on src/components/asset-list/RecyclerAssetList2/index.tsx
> +// //////////////////////////////////////////////////////////
Shall we delete this?

2022-10-07 18:08 UTC, BrodyHughes requested changes
Still checking over core functionality, but have noticed an overlap with status bars + our top menu items on Android devices. Screenshots are a Pixel 6 w/ Android 13 and a Samsung S10 with Android 12.
![Screenshot_20221007-130629_Rainbow](https://user-images.githubusercontent.com/41711440/194622027-2dfa0bb6-8839-4b18-b39d-0b7bc10d872b.jpg)
![Screenshot_20221007-130242](https://user-images.githubusercontent.com/41711440/194622030-ae946b12-1778-4707-93a2-ae021c8a13f8.png)

2022-10-11 16:34 UTC, BrodyHughes commented
The animation between switching wallets as seen [here
](https://github.com/rainbow-me/rainbow/pull/4106) seems to not be working. Also get the add cash screen sometimes before the wallet loads.
https://user-images.githubusercontent.com/41711440/195148547-65b0fe5a-4268-40be-a68d-b946c200b2dc.mov

2022-10-11 21:56 UTC, jxom commented
@BrodyHughes – animation seems to work on my device.
the add cash screen is currently in the app store version too, not sure if it is in the scope of this PR.

2022-10-12 16:56 UTC, BrodyHughes commented
A few more visual bugs:
1. The shadow on the pfp circle is different on the homescreen vs the txn screen (homescreen is colored, txn screen is black). Transparent backgrounds on pfps also look like they are treated slightly different.
<img width="200" alt="Screen Shot 2022-10-12 at 11 47 15 AM" src="https://user-images.githubusercontent.com/41711440/195402393-80d0798c-863e-48c2-bb5f-74956d39e162.png">
<img width="200" alt="Screen Shot 2022-10-12 at 11 47 24 AM" src="https://user-images.githubusercontent.com/41711440/195402401-f89d9b05-1e75-44fc-bc33-d84e81a372c6.png">

2. On Android there is no pull down animation to refresh like there is on iOS (just a loading circle).
https://user-images.githubusercontent.com/41711440/195403013-4ad5d969-84ce-43d1-8df5-c724d225949e.mp4

3. On Android is there supposed to be a wallet switch animation? 
4. On Android the height of the menu items looks better but is still a little high. It overlaps with the camera on some devices.
<img width="200" alt="Screen Shot 2022-10-12 at 11 47 24 AM" src="https://user-images.githubusercontent.com/41711440/195403107-1ff16cfc-9b6f-4265-91c8-dfc1d8eb5183.jpeg">

2022-10-18 21:00 UTC, estrattonbailey approved these changes

2022-10-19 20:36 UTC, skylarbarrera approved these changes

2022-10-19 20:37 UTC, merged