fix send emoji
rainbow-me/rainbow pull request #4227
Opened 2022-09-29 18:31 UTC by skylarbarrera

Fixes RNBW-4553
Figma link (if any):

## What changed (plus any additional context for devs)
removed feature flag and fixed the logic

## Screen recordings / screenshots

https://cloud.skylarbarrera.com/Screen-Recording-2022-09-29-14-27-08.mp4

^ ignore the double of addresses in the list, I used that for testing

## What to test

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

2022-09-30 13:48 UTC, estebanmino commented
not coming from this PR but found another instance of this happening, while adding contact from send sheet https://www.loom.com/share/5f0407241e27490c8bf25cd8dd858217

2022-09-30 16:34 UTC, skylarbarrera commented
updated PoW: https://cloud.skylarbarrera.com/Screen-Recording-2022-09-30-12-32-27.mp4

2022-09-30 18:44 UTC, estebanmino commented on src/components/contacts/SwipeableContactRow.js
> +  console.log(color);
uh

2022-09-30 22:26 UTC, estebanmino approved these changes

2022-10-03 15:22 UTC, derHowie approved these changes
lgtm

2022-10-03 18:20 UTC, ibrahimtaveras00 requested changes
Still seeing the issue @estebanmino reported above about the "add contact" flow not updating

https://user-images.githubusercontent.com/41752922/193649828-67861a2a-7ec1-4e5d-8819-e0c11a6b3b93.mov

Also, if I change from an emoji to an image in my library, the send sheet doesn't update

https://user-images.githubusercontent.com/41752922/193650099-8903b2f8-0dc8-4ae1-955f-9961b0c7d081.mov

2022-10-03 18:37 UTC, skylarbarrera commented
@ibrahimtaveras00 these are both expected behavior unfortunately, we do not check imported/watched wallets here which is causing this behavior 

checked a build from earlier this year and same thing

2022-10-03 19:43 UTC, ibrahimtaveras00 approved these changes
in light of above comment, this is good now 👍🏽

2022-10-03 19:47 UTC, merged