Update discover home
rainbow-me/rainbow pull request #4384
Opened 2022-11-10 22:45 UTC by benisgold

Fixes APP-207

## What changed (plus any additional context for devs)
- updated layout of discover home w/ new cards

## Screen recordings / screenshots
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-11-10 at 14 36 28](https://user-images.githubusercontent.com/15272675/201221801-3f898657-8529-4710-b7d6-e77c4febc449.png)
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-11-10 at 14 39 13](https://user-images.githubusercontent.com/15272675/201221813-2bb05918-0b3c-427e-b613-efea93b841fa.png)

## What to test

2022-11-10 22:46 UTC, benisgold commented on src/components/cards/utils/constants.ts
> +export const cryptoAndWalletsCard: LearnCardDetails = {
will possibly refactor / get rid of this file when i make the wallet screen changes

2022-11-14 01:43 UTC, skylarbarrera approved these changes
🚀

2022-11-14 17:10 UTC, skylarbarrera commented
looks like this needs some e2e magic

2022-11-15 11:34 UTC, jkadamczyk requested changes
I reviewed the code and it looks grweat, I also did some dev QA, I shared a loom recording on Linear

2022-11-15 20:52 UTC, estrattonbailey approved these changes

2022-11-15 20:52 UTC, estrattonbailey commented on src/components/cards/LearnCard.tsx
> +  type: CardType;
Nice!

2022-11-15 22:51 UTC, benisgold commented on src/components/cards/LearnCard.tsx
> +  type: CardType;
haha thank u

2022-11-15 22:54 UTC, benisgold commented
@jkadamczyk i fixed all the things in your loom vid! thanks for noting those

2022-11-16 10:55 UTC, jkadamczyk approved these changes
Looks great!

Very smart with pointerEvents="none" 👍

2022-11-16 16:03 UTC, merged