chore: remove com.polidea.reactnativeble.BlePackage import
rainbow-me/rainbow pull request #4518
Opened 2023-01-04 21:07 UTC by skylarbarrera

fixes android builds, dep is unneeded and unused with the latest of the BLEpackage
## What changed (plus any additional context for devs)

## Screen recordings / screenshots
https://cloud.skylarbarrera.com/Screen-Shot-2023-01-04-16-07-14.20.png

## What to test

2023-01-04 21:08 UTC, ibrahimtaveras00 approved these changes

2023-01-05 11:44 UTC, jkadamczyk approved these changes

2023-01-05 11:57 UTC, jkadamczyk commented
I mean it builds for me but there's an error when I create a new wallet, I guess building in release mode may crash the app, or it will be silent but still erroring out

2023-01-05 11:58 UTC, jkadamczyk requested changes
We probably need to integrate the BLE library since it is a peer dependency of the ledger library

2023-01-05 12:04 UTC, jkadamczyk commented
But seems like you actually do not need this import as well, just the package is not in package.json as well which gives me errors

2023-01-05 16:36 UTC, skylarbarrera commented
seeing the same thing @jkadamczyk just added ty king

2023-01-09 11:58 UTC, jkadamczyk approved these changes

2023-01-09 13:38 UTC, jinchung approved these changes
🌮

2023-01-09 13:45 UTC, merged