Fix safe area insets and remove old dependencies
rainbow-me/rainbow pull request #4574
Opened 2023-01-24 21:23 UTC by benisgold

Fixes APP-####

## What changed (plus any additional context for devs)
- fix safe area insets (this makes sheets look normal on newer iPhones, instead of overlapping with dynamic island/notch)
- remove react-native-safe-area-view
- remove x

## Screen recordings / screenshots

## What to test

2023-01-26 17:57 UTC, estrattonbailey approved these changes

2023-01-30 12:04 UTC, jkadamczyk approved these changes

2023-02-06 15:19 UTC, skylarbarrera commented
would love some QA on this since the last iteration had to be reverted cc @BrodyHughes @ibrahimtaveras00

2023-02-15 20:09 UTC, BrodyHughes requested changes
found a couple issues this causes on some android sheets. connected with ben via dms.

2023-04-18 20:28 UTC, BrodyHughes approved these changes
he fixed the thing ! !

2023-04-18 21:26 UTC, merged