Eric/app 517 integrate new auth sdk
rainbow-me/rainbow pull request #4777
Opened 2023-04-05 18:17 UTC by estrattonbailey

Fixes APP-####

## What changed (plus any additional context for devs)

## Screen recordings / screenshots

## What to test

2023-04-07 18:47 UTC, estrattonbailey commented on src/walletConnect/index.tsx
> +  proposal: Web3WalletTypes.SessionProposal;
Might as well source types from the main package, not the individual libraries.

2023-04-07 18:48 UTC, estrattonbailey commented on src/walletConnect/index.tsx
> +  client.on('auth_request', handler);
Since auth is a type of pairing, this is ensuring that we handle clearing the session timeout for auth_request too.

2023-04-07 18:48 UTC, estrattonbailey commented on src/walletConnect/index.tsx
> +export async function onAuthRequest(event: Web3WalletTypes.AuthRequest) {
Only net-new stuff in this file is in here

2023-04-07 18:49 UTC, estrattonbailey commented on src/walletConnect/types.ts
> +}) => Promise<AuthRequestAuthenticateResult>;
Handy dandy

2023-04-10 09:39 UTC, jkadamczyk approved these changes

2023-04-10 09:40 UTC, jkadamczyk commented
Will test soon

2023-04-20 12:02 UTC, ibrahimtaveras00 requested changes
APP-553
APP-554
APP-555

2023-04-20 16:14 UTC, benisgold commented on src/walletConnect/sheets/AuthRequest.tsx
> +                  shadow="18px"
this seems to be working

2023-04-20 17:15 UTC, benisgold approved these changes

2023-04-24 15:18 UTC, skylarbarrera approved these changes
looks great got an open PR to fix the one issue

2023-04-25 23:34 UTC, ibrahimtaveras00 requested changes
All issues are resolved except for Issue 2 of APP-555

Basically, import the ledger wallet the normal way.  Then try to connect to it via WC v2 Auth flow while that wallet is selected in the switcher.

Android Flow: 

https://user-images.githubusercontent.com/41752922/234430062-0a478eab-0c4f-4283-bc37-dfc6c56dac8f.mov



Happens on iOS too: 

![IMG_3BD62739DE24-1](https://user-images.githubusercontent.com/41752922/234429952-11179711-203e-4e0b-9eff-63fde018ea46.jpeg)

2023-05-01 20:00 UTC, merged