fix: wc cold-start deeplinks
rainbow-me/rainbow pull request #4790
Opened 2023-04-13 17:06 UTC by estrattonbailey

Fixes APP-548

## What changed (plus any additional context for devs)
See ticket. This PR waits even longer before responding to a deeplink. Critically: it waits until _after_ we've reconnected to WC.

2023-04-19 17:30 UTC, estrattonbailey commented on src/utils/branch.ts
Only logging and formatting in this file.

2023-04-19 17:31 UTC, estrattonbailey commented on src/App.js
> +  }
This is the meat and potatoes of this PR

2023-04-19 18:24 UTC, estrattonbailey commented on src/App.js
> +  }
This is the meat and potatoes of this PR

2023-04-21 09:24 UTC, jkadamczyk approved these changes

2023-04-21 14:47 UTC, skylarbarrera approved these changes
🔥

2023-04-25 17:33 UTC, ibrahimtaveras00 requested changes
Following issues:

- https://linear.app/rainbow/issue/APP-567/[app-548-bug]-launching-a-txn-notification-from-cold-start-broken-on

- https://linear.app/rainbow/issue/APP-568/[app-548-bug]-launching-a-request-from-opensea-app-on-a-cold-start

- https://linear.app/rainbow/issue/APP-569/[app-548-bug]-launching-app-on-cold-start-from-wc-request-via-both-wc1

2023-04-26 20:13 UTC, estrattonbailey commented
/rebase

2023-04-28 16:03 UTC, estrattonbailey commented
/rebase

2023-04-28 20:11 UTC, merged