i18n: missing strings
rainbow-me/rainbow pull request #4983
Opened 2023-07-31 23:28 UTC by skylarbarrera

Fixes APP-####

## What changed (plus any additional context for devs)

## Screen recordings / screenshots

## What to test

2023-08-03 21:01 UTC, benisgold requested changes
loooks good except for smileys. there's 1 spot where there's a smiley in the english translation so at least that one should be changed before merge

2023-08-03 21:01 UTC, benisgold commented on src/languages/_english.json
> +      "today_caps": "Today :)",
more smileys

2023-08-03 21:01 UTC, benisgold commented on src/languages/_french.json
> +      "errors": {
missing smileys

2023-08-03 21:01 UTC, benisgold commented on src/languages/_french.json
> +        "profiles": "Profiles",
smiley!

2023-08-03 21:01 UTC, benisgold commented on src/languages/_french.json
> +      "card": {
:)

2023-08-04 15:51 UTC, skylarbarrera commented on src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
> +  console.log({ supportsVideo });
oops

2023-08-04 16:15 UTC, benisgold approved these changes

2023-09-01 16:40 UTC, merged