feat: adds zksync to network configuration
rainbow-me/rainbow pull request #5066
Opened 2023-09-20 16:42 UTC by dutterbutter

I am making this a **DRAFT PR** as there is an item I require assistance / context from Rainbow team for the following: 

1. What is `balanceCheckerAddress`? I see its a contract, and the comment suggests "Check all the ETH balances at once". I have left this field blank until further direction is provided. 

## What changed (plus any additional context for devs)
- Adds zkSync network configuration

## Screen recordings / screenshots

## What to test

2023-09-20 17:31 UTC, JackHamer09 requested changes

2023-09-20 17:31 UTC, JackHamer09 commented on src/networks/zksync.ts
> +    name: 'ZkSync',
```suggestion
    name: 'zkSync',
```

2023-09-20 17:31 UTC, JackHamer09 commented on src/resources/nfts/simplehash/types.ts
> +  ZkSync = 'zkSync',
```suggestion
  zkSync = 'zkSync',
```

2023-09-20 17:31 UTC, JackHamer09 commented on src/networks/types.ts
> +  zkSync = 'zkSync',
In some places I see network key as lowercase `zksync` and sometimes it's `zkSync`. Should we make all the same?

2023-10-12 21:11 UTC, dutterbutter commented
@benisgold hey there 👋 

I am hoping to finish up this PR, do you mind giving me some clarity on this variable "balanceCheckerAddress"?

2024-02-02 18:03 UTC, closed without merging