i18n: enable + analytics
rainbow-me/rainbow pull request #5074
Opened 2023-09-25 20:09 UTC by skylarbarrera

## What changed (plus any additional context for devs)

## Screen recordings / screenshots

## What to test

2023-09-29 23:50 UTC, ibrahimtaveras00 requested changes
https://linear.app/rainbow/issue/APP-822/i18n-qa-bug-epic

2023-10-05 15:08 UTC, ibrahimtaveras00 commented
Still a few outstanding issues, not sure if you want to count any of these as blockers or not for merging: 

- https://linear.app/rainbow/issue/APP-831/all-russian-translation-issues#comment-1033bf85 
- https://linear.app/rainbow/issue/APP-824/all-francais-translation-issues#comment-428ffe23
- https://linear.app/rainbow/issue/APP-823/all-spanish-translation-issues#comment-1e821959
- https://linear.app/rainbow/issue/APP-828/[android-only]-button-for-smol-balances-arrow-is-misaligned-both-in
- https://linear.app/rainbow/issue/APP-830/edit-icon-on-contact-shows-as-delete-icon

2023-10-12 18:38 UTC, benisgold approved these changes

2023-10-13 00:10 UTC, ibrahimtaveras00 approved these changes
outside of missing French translations, everything else was good 👍🏽

2023-10-13 14:11 UTC, merged