add WALLET_CONNECT_REDIRECT_SHEET navigation on connection
rainbow-me/rainbow pull request #5127
Opened 2023-10-17 23:01 UTC by walmat

Fixes APP-####

## What changed (plus any additional context for devs)
Add a follow-up sheet since iOS 17 broke our transfer back to app who requested connection/signature.

## Screen recordings / 

https://github.com/rainbow-me/rainbow/assets/6284525/b25875f4-de49-4b12-a680-8048df708e36

screenshots

## What to test
Not much to test here other than that Android has no breaking changes

2023-10-18 17:33 UTC, skylarbarrera requested changes

2023-10-20 16:03 UTC, skylarbarrera requested changes

2023-10-20 16:03 UTC, skylarbarrera commented on src/screens/WalletConnectApprovalSheet.js
> +    if (ios) {
I still think this is going to be an issue 🤔 

this will be called still afaik: maybeGoBackAndClearHasPendingRedirect

2023-10-20 16:12 UTC, walmat commented on src/screens/WalletConnectApprovalSheet.js
> +    if (ios) {
Oh i swore I pushed this change up.. Let me do that

2023-10-20 17:32 UTC, walmat commented
Going to combine https://linear.app/rainbow/issue/APP-869/connection-prompt-doesnt-dismiss-automatically into this issue since they're simple and related.

2023-10-20 18:04 UTC, skylarbarrera approved these changes

2023-10-20 18:07 UTC, ibrahimtaveras00 requested changes
- Prompt doesn't auto dismiss = https://linear.app/rainbow/issue/APP-869/connection-prompt-doesnt-dismiss-automatically

- Also noticing signing & confirming txn's don't have a sheet = https://linear.app/rainbow/issue/APP-827/automatic-wc-redirect-back-to-browser-is-broken-on-ios-17#comment-4206db32

2023-10-20 20:14 UTC, walmat commented
Updated screen recordings:

https://github.com/rainbow-me/rainbow/assets/6284525/25648b72-eb01-4165-9252-bc46b5e71894

https://github.com/rainbow-me/rainbow/assets/6284525/a9375fd5-3a66-4adb-b1cc-a5780eae1c44

2023-10-20 21:51 UTC, ibrahimtaveras00 approved these changes
✅

2023-10-20 21:52 UTC, merged