swaps: bump sdk
rainbow-me/rainbow pull request #5583
Opened 2024-04-02 14:47 UTC by skylarbarrera

## What changed (plus any additional context for devs)
bumping swap sdk for blast + zora swaps

## Screen recordings / screenshots

## What to test

2024-04-02 14:59 UTC, benisgold approved these changes

2024-04-02 15:05 UTC, dereknelson approved these changes

2024-04-04 15:41 UTC, ibrahimtaveras00 requested changes
https://rainbowhaus.slack.com/archives/C0468CDBE75/p1712168419912059?thread_ts=1712091889.898369&cid=C0468CDBE75

2024-04-04 18:34 UTC, ibrahimtaveras00 approved these changes
All gucci now ✅  = https://rainbowhaus.slack.com/archives/C0468CDBE75/p1712255479014529?thread_ts=1712091889.898369&cid=C0468CDBE75

2024-04-05 17:07 UTC, merged