Disable flashbots toggle on appropriate chains
rainbow-me/rainbow pull request #5812
Opened 2024-06-04 16:18 UTC by walmat

Fixes APP-1560

## What changed (plus any additional context for devs)

## Screen recordings / screenshots

## What to test

2024-06-04 16:38 UTC, walmat commented on src/__swaps__/screens/Swap/hooks/useSwapSettings.ts
> +  };
important to note this doesn't effect persistence in the js store since it doesn't update that (which is intended).

2024-06-05 05:11 UTC, jinchung commented on src/__swaps__/screens/Swap/hooks/useSwapSettings.ts
> +    if (asset?.chainId === ChainId.mainnet) {
we should avoid network-specific logic like this - the source of truth for if flashbots is enabled is in the `networks` config (under `features` -> `flashbots`)

2024-06-05 20:25 UTC, jinchung requested changes
Comments inline

2024-06-05 20:25 UTC, jinchung commented on src/__swaps__/screens/Swap/hooks/useSwapSettings.ts
> +  const checkIfFlashbotsIsEnabledOnSelectedInputAssetChain = (asset: ExtendedAnimatedAssetWithColors | null) => {
we can remove this function entirely and just set the `value` in the `ReviewPanel` to `const flashbotsToggleValue = useDerivedValue(() => isFlashbotsSupportedNetwork && SwapSettings.flashbots.value);`

2024-06-05 21:09 UTC, jinchung approved these changes
🌮

2024-06-05 21:13 UTC, jinchung commented
Testing scenarios:
- default with mainnet asset -> review panel should show flashbots disabled but toggleable
- switching to another mainnet asset -> flashbots disabled but toggleable 
- toggling flashbots on -> switching to another mainnet asset -> flashbots enabled and toggleable
- switching to a non-mainnet asset -> flashbots disabled and not toggleable
- switching to a mainnet asset -> flashbots enabled and toggleable
- toggling flashbots off -> switching to another mainnet asset -> flashbots disabled and toggleable
- switching to non-mainnet asset -> flashbots disabled and not toggleable
- close the swaps flow -> come back to mainnet default -> flashbots disabled and toggleable
- turn on flashbots -> close the swaps flow -> come back to mainnet default -> flashbots enabled and toggleable

2024-06-06 15:17 UTC, merged