Add max swappable amount on balance badge tap
rainbow-me/rainbow pull request #5947
Opened 2024-07-23 15:55 UTC by walmat

Fixes APP-1557

## What changed (plus any additional context for devs)
Adds balance badge press setting max swappable amount for asset if user has balance.

Note I also added the functionality to output balance badge.

## Screen recordings / screenshots

## What to test

2024-07-23 17:26 UTC, greg-schrammel approved these changes
nice

2024-07-24 05:34 UTC, jinchung requested changes
1. I think having this functionality on the output badge will not be that useful @christianbaroni  if you have thoughts here
2. This adds duplicate code, can we have the `onSetMaxBalance` worklet pulled out separately and shared across the `SwapSlider` and `SwapInputAsset`? Assuming we don't do the output asset, this simplifies it even more. This is for maintenance considerations going forward, if we need to update this logic, it's easier to just update in one place than in two or three.

2024-07-25 21:09 UTC, jinchung commented on src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
> +  outputQuotesAreDisabled,
this param no longer needed and the corresponding changes in `swap-provider` also not needed

2024-07-25 22:36 UTC, jinchung approved these changes
🌮

2024-07-25 22:36 UTC, merged