Copy/Paste fixes
rainbow-me/rainbow pull request #5953
Opened 2024-07-24 18:24 UTC by greg-schrammel

Fixes APP-####

## What changed (plus any additional context for devs)

- fixes output being overwritten on quote refetch after paste by setting `inputMethod` to the right field on paste
-  fixes dapp browser new tab and done buttons, by passing nothing/undefined to the fns args, now GestureHandler `onPress` calls the handler with the `event` and this event was being passed as arg to those functions, making they misbehave 

## Screen recordings / screenshots

## What to test

2024-07-25 13:29 UTC, walmat reviewed
I'm not sure I understand the change made to the GestureHandlerV1Button that prevents us from being able to pass a worklet function directly to the onPressWorklet prop.

2024-07-25 17:54 UTC, jinchung requested changes
adding a note from Christian: test against when numbers have commas

2024-07-26 04:48 UTC, christianbaroni commented
> I'm not sure I understand the change made to the GestureHandlerV1Button that prevents us from being able to pass a worklet function directly to the onPressWorklet prop.

+1, would rather we address the underlying issue making the extra wrapper necessary, if it is actually necessary currently

2024-07-29 15:48 UTC, greg-schrammel commented
> > I'm not sure I understand the change made to the GestureHandlerV1Button that prevents us from being able to pass a worklet function directly to the onPressWorklet prop.
> 
> +1, would rather we address the underlying issue making the extra wrapper necessary, if it is actually necessary currently

it is not being used so I removed the event arg on gesture handler v1 callbacks

2024-07-30 17:20 UTC, greg-schrammel commented on src/__swaps__/screens/Swap/components/GestureHandlerV1Button.tsx
> +      if (onPressJS) runOnJS(onPressJS)();
these `e` were not used anywhere

2024-08-02 17:59 UTC, walmat approved these changes

2024-08-02 18:51 UTC, christianbaroni approved these changes

2024-08-02 18:51 UTC, jinchung approved these changes
🌮

2024-08-02 18:51 UTC, merged