Fixes opacity on mwp sign txn sheet
rainbow-me/rainbow pull request #6083
Opened 2024-09-05 19:08 UTC by walmat

Fixes APP-1852

## What changed (plus any additional context for devs)
fixes opacity on route source for mwp

## Screen recordings / screenshots

## What to test

2024-09-05 19:19 UTC, greg-schrammel approved these changes
✌️

2024-09-06 13:43 UTC, brunobar79 requested changes
Could you please add PoW and testing instructions?

2024-09-06 13:43 UTC, brunobar79 commented on src/navigation/config.tsx
> +        route?.params?.source === RequestSource.WALLETCONNECT || route?.params?.source === RequestSource.MOBILE_WALLET_PROTOCOL ? 1 : 0.7,
```suggestion
        [RequestSource.WALLETCONNECT, RequestSource.MOBILE_WALLET_PROTOCOL].includes(route?.params?.source) ? 1 : 0.7
```

2024-09-06 14:51 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/APP-1852/cd5af652b1e8c86a9af8bda405af53a2e2e5fa8e.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/APP-1852/cd5af652b1e8c86a9af8bda405af53a2e2e5fa8e.ipa) for cd5af652b1e8c86a9af8bda405af53a2e2e5fa8e

2024-09-06 17:14 UTC, benisgold approved these changes

2024-09-09 15:05 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/APP-1852/ca81103215d3ace6c4f15a029e7d79312363c539.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/APP-1852/ca81103215d3ace6c4f15a029e7d79312363c539.ipa) for ca81103215d3ace6c4f15a029e7d79312363c539

2024-09-09 17:17 UTC, jinchung commented
adding source convo: https://rainbowhaus.slack.com/archives/C02C2FVC6N6/p1725561738782969

2024-09-09 17:38 UTC, merged