Claimables: Claim Panel UI
rainbow-me/rainbow pull request #6092
Opened 2024-09-09 16:06 UTC by benisgold

Fixes APP-####

## What changed (plus any additional context for devs)
created the ui for claiming a claimable

will clean it up more / add i18n as i plug in functionality

## Screen recordings / screenshots

https://github.com/user-attachments/assets/ba2f6229-19a6-478e-9454-b1824d6fdb90

## What to test
have not tested on android yet, had to update jdk which busted my builds

2024-09-10 16:43 UTC, greg-schrammel commented on src/components/asset-list/RecyclerAssetList2/Claimable.tsx
> +      select: data => data?.filter(claimable => claimable.uniqueId === uniqueId),
if we are only using one claimable isn't it better to do a `data?.find`?

2024-09-12 14:49 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@benisgold/claim-ui/4128db484d3d71484fb424535c9b47f63cd98f35.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@benisgold/claim-ui/4128db484d3d71484fb424535c9b47f63cd98f35.ipa) for 4128db484d3d71484fb424535c9b47f63cd98f35

2024-09-12 17:04 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@benisgold/claim-ui/3cb10a4f595c48cbff5641b5a80dfc29dcfe1ec5.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@benisgold/claim-ui/3cb10a4f595c48cbff5641b5a80dfc29dcfe1ec5.ipa) for 3cb10a4f595c48cbff5641b5a80dfc29dcfe1ec5

2024-09-12 17:12 UTC, walmat commented on src/screens/claimables/ClaimClaimablePanel.tsx
> +// import { ContextMenuButton } from '@/components/context-menu';
rm

2024-09-12 17:14 UTC, walmat commented on src/screens/claimables/ClaimClaimablePanel.tsx
> +  // const onShowActionSheet = useCallback(() => {}, []);
rm if not needed

2024-09-12 17:14 UTC, walmat commented on src/screens/claimables/ClaimClaimablePanel.tsx
> +        {/* <Box alignItems="center" gap={20}> */}
rm if not needed

2024-09-12 17:14 UTC, walmat commented on src/screens/claimables/ClaimClaimablePanel.tsx
> +        {/* </Box> */}
rm if not needed

2024-09-12 17:14 UTC, walmat commented on src/screens/claimables/ClaimClaimablePanel.tsx
> +              {`$0.01 to claim on ${chainName}`}
is this supposed to be static?

2024-09-12 17:15 UTC, walmat commented on src/screens/claimables/ClaimClaimablePanel.tsx
> +                {'Claim'}
```suggestion
                Claim
```

2024-09-12 17:15 UTC, walmat commented on src/screens/claimables/ClaimClaimablePanel.tsx
> +  const chainName = ChainNameDisplay[claimable.chainId];
should we have a fallback here?

2024-09-12 17:16 UTC, walmat commented on src/screens/claimables/ClaimClaimablePanel.tsx
> +};
can you move these to `RootStackParamList`
https://github.com/rainbow-me/rainbow/blob/dd030ca15cc86207c1f5f78d611d20ed07891f40/src/navigation/types.ts#L19

2024-09-12 17:17 UTC, walmat requested changes
some changes but overall looking good

2024-09-26 14:23 UTC, closed without merging