WC migration to WalletKit
rainbow-me/rainbow pull request #6163
Opened 2024-10-02 22:25 UTC by brunobar79

Fixes APP-1716
## What changed (plus any additional context for devs)

- Bumped all wc packages to latest version
- Migrated Web3Wallet to WalletKit package

## Screen recordings / screenshots
TBD

## What to test
WC v2

2024-10-04 00:45 UTC, walmat commented on src/walletConnect/index.tsx
> +  const { metadata } = (proposal as WalletKitTypes.SessionProposal).params.proposer;
```suggestion
  const { metadata } = proposal.params.proposer;
```

2024-10-04 00:46 UTC, walmat commented on src/walletConnect/index.tsx
> +              console.log('[WC DEBUG] rejected proposal');
use logger or remove if not needed

2024-10-04 00:47 UTC, walmat commented on src/walletConnect/index.tsx
> +              console.log('[WC DEBUG] session approved');
use logger or remove if not needed

2024-10-04 00:47 UTC, walmat commented on src/walletConnect/index.tsx
> +        console.log('[WC DEBUG] executing callback');
use logger or remove if not needed

2024-10-04 00:47 UTC, walmat commented on src/walletConnect/index.tsx
> +        console.log('[WC DEBUG] got client');
use logger or remove if not needed

2024-10-04 00:47 UTC, walmat commented on src/walletConnect/index.tsx
> +          console.log('[WC DEBUG] approved true');
use logger or remove if not needed

2024-10-04 00:47 UTC, walmat commented on src/walletConnect/index.tsx
> +            console.log('[WC DEBUG] try');
use logger or remove if not needed

2024-10-04 00:47 UTC, walmat commented on src/walletConnect/index.tsx
> +              console.log('[WC DEBUG] namespaces success');
use logger or remove if not needed

2024-10-04 00:47 UTC, walmat commented on src/walletConnect/index.tsx
> +            console.log('[WC DEBUG] catch', e);
use logger or remove if not needed

2024-10-04 00:47 UTC, walmat commented on src/walletConnect/index.tsx
> +          console.log('[WC DEBUG] not approved');
use logger or remove if not needed

2024-10-04 00:48 UTC, walmat commented on src/walletConnect/index.tsx
> +  // @ts-ignore Can be fixed once we wipe wc v1 from the codebase
is this legacy now?

2024-10-04 00:48 UTC, walmat commented on src/walletConnect/index.tsx
> +        // @ts-ignore Can be fixed once we wipe wc v1 from the codebase
is this legacy now?

2024-10-04 00:48 UTC, walmat commented on src/walletConnect/index.tsx
> +        // @ts-ignore Can be fixed once we wipe wc v1 from the codebase
is this legacy now?

2024-10-04 00:49 UTC, walmat commented on src/walletConnect/index.tsx
>      event?.verifyContext?.origin || event.params.requester.metadata.url;
this is `event?.verifyContext?.verified?.origin`

2024-10-04 00:50 UTC, walmat commented on src/walletConnect/index.tsx
>          verifiedData: event?.verifyContext,
same here. use `event?.verifyContext?.verified`

2024-10-04 00:50 UTC, walmat commented on src/walletConnect/index.tsx
> +      // @ts-ignore Can be fixed once we wipe wc v1 from the codebase
is this legacy now?

2024-10-04 00:59 UTC, walmat requested changes
few comments. I think we need to explore what to do with all of the `@ts-ignore` in this file

2024-10-04 00:59 UTC, walmat commented on src/walletConnect/index.tsx
>      event?.verifyContext?.origin || event.params.requester.metadata.url;
can also remove the `@ts-ignore` after you make that change

2024-10-04 00:59 UTC, walmat commented on src/walletConnect/index.tsx
>          verifiedData: event?.verifyContext,
and remove `@ts-ignore`

2024-10-04 17:42 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/wc-walletkit/57150b05e769c078754af0aa6d137f598f5589b8.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/wc-walletkit/57150b05e769c078754af0aa6d137f598f5589b8.ipa) for 57150b05e769c078754af0aa6d137f598f5589b8

2024-10-04 22:40 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/wc-walletkit/afba60528a03aa2fd9ebcc7d5317deab3356782b.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/wc-walletkit/afba60528a03aa2fd9ebcc7d5317deab3356782b.ipa) for afba60528a03aa2fd9ebcc7d5317deab3356782b

2024-10-04 23:46 UTC, walmat approved these changes

2024-10-07 13:01 UTC, derHowie approved these changes

2024-10-07 15:57 UTC, merged