fix: wallet telemetry identify
rainbow-me/rainbow pull request #6258
Opened 2024-11-08 21:28 UTC by DanielSinclair

Fixes APP-1956

## What changed (plus any additional context for devs)
- added `walletType` param to `identify` and Sentry user
- setting up Sentry and Rudderstack identify in `useInitializeWallet` to absorb wallet switches
- added `getWalletContext` util to prepare hashes and wallet types consistently throughout the codebase
- added `walletContext` overrides in `track` and `screen` to support scenarios where the actioned wallet is different than the global selected wallet

## Screen recordings / screenshots

## What to test
- confirmed proper hash switching on Rudderstack's side ✅ 
- `walletType` appears to be undefined directly after import because of the following snippet; alternative approach may be necessary 
```
const { wallets } = store.getState();
const wallet = findWalletWithAccount(wallets.wallets || {}, address);
```

2024-11-20 17:18 UTC, brunobar79 requested changes
Looks great but there's a lint error. Will approve after that!

2024-11-21 18:34 UTC, DanielSinclair commented
@brunobar79 Done ✅

2024-11-22 00:28 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@daniel/wallethash/60032a51c1a9d71f7f1e1131016cd9eadf2a6227.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@daniel/wallethash/60032a51c1a9d71f7f1e1131016cd9eadf2a6227.ipa) for 60032a51c1a9d71f7f1e1131016cd9eadf2a6227

2024-11-22 20:08 UTC, brunobar79 approved these changes

2024-11-22 21:02 UTC, BrodyHughes approved these changes
Checked:
- importing and switching wallets
- connecting to a dapp
- accepting / rejecting txns

walletAddressHash and walletType both look consistent and the events seems to populate as expected!

2024-11-22 21:07 UTC, merged