NFT checker 2.0
rainbow-me/rainbow pull request #6293
Opened 2024-12-02 23:24 UTC by brunobar79

Fixes APP-1629

## What changed (plus any additional context for devs)
- Updated the contract address of the NFT Checker 2.0 with ERC1155 support
- Added additional networks (Avalancha / Gnosis)

## Screen recordings / screenshots
None

## What to test
- Delete the app, Install testflight and make sure you can still unlock any previous icon

2024-12-04 00:20 UTC, ibrahimtaveras00 requested changes
App no longer shows unlocked icons on both OS's

2024-12-13 03:44 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/nft-checker-2.0/60639a2bafa34c698723a36bc349596ea188846e.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/nft-checker-2.0/60639a2bafa34c698723a36bc349596ea188846e.ipa) for 60639a2bafa34c698723a36bc349596ea188846e

2024-12-13 14:04 UTC, walmat approved these changes

2024-12-13 19:01 UTC, derHowie approved these changes

2024-12-13 20:07 UTC, benisgold approved these changes

2024-12-13 20:10 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/nft-checker-2.0/f87eec473d55a75da4930a41692dd3d387eb87cf.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/nft-checker-2.0/f87eec473d55a75da4930a41692dd3d387eb87cf.ipa) for f87eec473d55a75da4930a41692dd3d387eb87cf

2024-12-13 20:25 UTC, merged