Chain Badge consolidation & backend delivery
rainbow-me/rainbow pull request #6328
Opened 2024-12-12 18:12 UTC by walmat

Fixes APP-####

## What changed (plus any additional context for devs)

## Screen recordings / screenshots

## What to test

2024-12-17 20:08 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/31c82d1bc08f2ea3c809470e617f74e3496bb5bf.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/31c82d1bc08f2ea3c809470e617f74e3496bb5bf.ipa) for 31c82d1bc08f2ea3c809470e617f74e3496bb5bf

2024-12-18 19:14 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/5f8f02847174ab58ca4a47bed33035e27f76530c.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/5f8f02847174ab58ca4a47bed33035e27f76530c.ipa) for 5f8f02847174ab58ca4a47bed33035e27f76530c

2024-12-19 22:04 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/a282bd69228370a0a3db72b7c9499dda5f0f23c9.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/a282bd69228370a0a3db72b7c9499dda5f0f23c9.ipa) for a282bd69228370a0a3db72b7c9499dda5f0f23c9

2024-12-20 13:21 UTC, ibrahimtaveras00 requested changes
https://linear.app/rainbow/issue/APP-2216/chain-badge-consolidation-and-backend-delivery-6328-qa-bug-epic

2024-12-23 20:06 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/c3048bc76e9923ab3bd5a30a7ff97642bb1f054a.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/c3048bc76e9923ab3bd5a30a7ff97642bb1f054a.ipa) for c3048bc76e9923ab3bd5a30a7ff97642bb1f054a

2024-12-27 09:56 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/a22001af2e97f757752cc76a95e65906d8f874ac.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/a22001af2e97f757752cc76a95e65906d8f874ac.ipa) for a22001af2e97f757752cc76a95e65906d8f874ac

2025-01-06 17:52 UTC, derHowie approved these changes
Lgtm, went through most of the QA checklist. Initially I was going to post the PoW screenshots here but it would probably clutter the thread. I have them if needed.

I checked 85% of the QA checklist and didn't see any issues other than zksync era missing an icon and the `avaiable on other networks` badges looking off in the image below:
<img width="357" alt="Screenshot 2025-01-06 at 12 38 11 PM" src="https://github.com/user-attachments/assets/6659192b-f5af-4bfe-bb94-6253b9d64173" />

2025-01-06 17:52 UTC, derHowie commented on src/components/ExchangeTokenRow.tsx
> +
rm?

2025-01-06 17:55 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/d5615d1efc1dcc3d2e072ac454e864e336f662d9.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/d5615d1efc1dcc3d2e072ac454e864e336f662d9.ipa) for d5615d1efc1dcc3d2e072ac454e864e336f662d9

2025-01-06 19:57 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/d8624f2364c8f6ba5c7260ce179f3098c50b196e.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/d8624f2364c8f6ba5c7260ce179f3098c50b196e.ipa) for d8624f2364c8f6ba5c7260ce179f3098c50b196e

2025-01-06 21:38 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/37197592755f4cdb2129dbb5595ab2501df53823.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/37197592755f4cdb2129dbb5595ab2501df53823.ipa) for 37197592755f4cdb2129dbb5595ab2501df53823

2025-01-07 16:39 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/62069b2ec58b3f21af5dae6a6da1144eb0166d95.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/62069b2ec58b3f21af5dae6a6da1144eb0166d95.ipa) for 62069b2ec58b3f21af5dae6a6da1144eb0166d95

2025-01-07 18:16 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/9be06c70f7c7b435145e1e013b5f43b7e9a4a3cb.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/9be06c70f7c7b435145e1e013b5f43b7e9a4a3cb.ipa) for 9be06c70f7c7b435145e1e013b5f43b7e9a4a3cb

2025-01-09 00:05 UTC, ibrahimtaveras00 approved these changes
Bug fixes all look good on both OS's, QA Passed ✅

2025-01-10 17:21 UTC, walmat commented
Waiting to merge until @christianbaroni introduces a few positioning changes to the ChainImage component

2025-01-16 21:20 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/7c2c08a7a19175272cf0cf7530ffc56746780434.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/7c2c08a7a19175272cf0cf7530ffc56746780434.ipa) for 7c2c08a7a19175272cf0cf7530ffc56746780434

2025-01-17 12:07 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/d8afaab004f70fa36f5e3888e36d2134dbb4b5ea.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/backend-chain-badge/d8afaab004f70fa36f5e3888e36d2134dbb4b5ea.ipa) for d8afaab004f70fa36f5e3888e36d2134dbb4b5ea

2025-01-17 18:43 UTC, walmat commented on src/components/expanded-state/asset/ChartExpandedState.js
> +      {data?.networks && assetWithPrice && (
```suggestion
      {data?.networks && !hasBalance && (
```

2025-01-17 22:10 UTC, derHowie approved these changes
2nd round lgtm

2025-01-17 22:26 UTC, merged