Fix NFT save
rainbow-me/rainbow pull request #6356
Opened 2024-12-19 19:31 UTC by brunobar79

Fixes APP-1782

## What changed (plus any additional context for devs)
- The library we were using doesn't support downloading remote nfts so we had to download it first and then we're being able to save it to the camera roll
- The profile links we were building were no longer working. Fixed those and now "view on rainbow.me" and sharing too.
however the website has some issues on mobile were the popup that shows the specific NFT doesn't work but that's out of scope.

## Screen recordings / screenshots

https://github.com/user-attachments/assets/f7b5c8f5-140c-494e-bf59-48d8637a80f6

## What to test
- Grab any NFT and save it.
- Try to share it or view on rainbow.me - then verify that link works fine on desktop (mobile won't work bc of the website)

2024-12-19 22:06 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/fix-nft-save/244f4a8a1f60a4472fcdf92006332844c3c70af1.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/fix-nft-save/244f4a8a1f60a4472fcdf92006332844c3c70af1.ipa) for 244f4a8a1f60a4472fcdf92006332844c3c70af1

2024-12-31 19:36 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/fix-nft-save/c5e9cbadf55af132a6fc7d476c68bb3ff8d2771b.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/fix-nft-save/c5e9cbadf55af132a6fc7d476c68bb3ff8d2771b.ipa) for c5e9cbadf55af132a6fc7d476c68bb3ff8d2771b

2024-12-31 22:02 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/fix-nft-save/6aee56be22f2479afdf1e4e1c09d75692808a1ee.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/fix-nft-save/6aee56be22f2479afdf1e4e1c09d75692808a1ee.ipa) for 6aee56be22f2479afdf1e4e1c09d75692808a1ee

2025-01-02 17:06 UTC, ibrahimtaveras00 requested changes
works fine on iOS, however, when I attempt to test on Android device, I see a notification from the download manager that the download was unsuccessful 

seen here: 

https://github.com/user-attachments/assets/25ca2ee9-8f43-440d-856a-18e81980b9bd

<img width="404" alt="Screenshot 2025-01-02 at 12 07 35 PM" src="https://github.com/user-attachments/assets/d256e48d-ec4a-4b59-b5fe-f8fe28a16f08" />

2025-01-03 15:09 UTC, walmat commented on src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
> +        }
Should we even show the save button if there's nothing to save?

2025-01-03 15:12 UTC, walmat requested changes
Same issue as Ibrahim described. iOS works well though

2025-01-08 22:46 UTC, brunobar79 commented
Android fixed here  @ibrahimtaveras00  @walmat 


https://github.com/user-attachments/assets/f24a0bea-3eb5-48b2-a34c-139ceb01fa52

2025-01-08 23:40 UTC, brunobar79 commented
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/fix-nft-save/0d1e462f8b22672c4b54690185984396ab1a7629.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/fix-nft-save/0d1e462f8b22672c4b54690185984396ab1a7629.ipa) for 0d1e462f8b22672c4b54690185984396ab1a7629

2025-01-09 00:12 UTC, walmat approved these changes

2025-01-09 00:22 UTC, ibrahimtaveras00 approved these changes
Fix looks good, QA Passed 👍🏽

2025-01-09 00:25 UTC, merged